apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-tomcat 
spec:
  rules:
      paths:
      - backend:
          serviceName: my-tomcat
          servicePort: 8080
        path: /my-tomcat
