apiVersion: extensions/v1
kind: Ingress
metadata:
  name: my-tomcat
spec:
  rules:
  - http:
      paths:
      - path: /my-tomcat
        backend:
          serviceName: my-tomcat
          servicePort: 80
